# Author :  Muhammad Ali Saagar

**Python Developer • Data Science • AI/ML Enthusiast**

### 🔗 Connect With Me

[![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AliMuhammad78)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/muhammad-ali-91294a290)

[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/ali98muhammad45)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@TechyBits20121)

[![Instagram](https://img.shields.io/badge/Instagram-Profile-E4405F?style=for-the-badge\&logo=instagram)](https://www.instagram.com/alisaagar6453/)
[![Facebook](https://img.shields.io/badge/Facebook-Profile-1877F2?style=for-the-badge\&logo=facebook)](https://www.facebook.com/profile.php?id=100089566913912)

[![Email](https://img.shields.io/badge/Email-Contact-D14836?style=for-the-badge\&logo=gmail)](mailto:alisaagar86@gmail.com)

---

## Key data Structures in Pandas 
1. Series 
2. DataFrame

In [ ]:
import pandas as pd 
import numpy as np

 # 📘 Pandas Series

A **Pandas Series** is a **one-dimensional labeled array** that can store data of any type, such as integers, floats, strings, or even Python objects.

Think of a Series as a **single column in a spreadsheet** or a **dictionary with ordered values**, where each value has an associated **index**.

## Key Characteristics

- One-dimensional data structure.
- Each element has an **index (label)**.
- Can store homogeneous or heterogeneous data.
- Built on top of NumPy arrays.
- Supports fast indexing, slicing, and vectorized operations.

## Syntax

```python
pd.Series(data, index=None, dtype=None, name=None)
```

## Example

```python
import pandas as pd

marks = pd.Series([85, 90, 78, 92])

print(marks)
```

**Output**

```text
0    85
1    90
2    78
3    92
dtype: int64
```

## Common Uses

- Storing a single column of data.
- Time-series data.
- Statistical analysis.
- Data preprocessing.
- Building DataFrames.

> **Note:** A **DataFrame** is simply a collection of one or more **Series** sharing the same index.

In [2]:
s = pd.Series([1, 3, 5, 7, 9])
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [3]:
s = pd.Series([1 , 3, 5, 7, 9], index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    3
c    5
d    7
e    9
dtype: int64

# 📘 Pandas DataFrame

A **Pandas DataFrame** is a **two-dimensional labeled data structure** used to store and manipulate tabular data. It consists of **rows** and **columns**, similar to an Excel spreadsheet or SQL table.

A DataFrame is built from one or more **Pandas Series**, where each column is a Series sharing the same index.

## Key Characteristics

- Two-dimensional (rows and columns).
- Each column can have a different data type.
- Columns have labels (column names).
- Rows have labels (index).
- Built on top of NumPy arrays.
- Supports fast indexing, filtering, sorting, grouping, and data analysis.

## Syntax

```python
pd.DataFrame(data, index=None, columns=None, dtype=None)
```

## Example

```python
import pandas as pd

students = {
    "Name": ["Ali", "Ahmed", "Sara"],
    "Age": [20, 22, 21],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(students)

print(df)
```

**Output**

```text
    Name  Age  Marks
0    Ali   20     85
1  Ahmed   22     90
2   Sara   21     88
```

## Common Uses

- Data cleaning and preprocessing.
- Reading and writing CSV, Excel, JSON, and SQL files.
- Data analysis and exploration.
- Filtering, sorting, and grouping data.
- Statistical analysis.
- Preparing datasets for Machine Learning.

## DataFrame vs Series

| Feature | Series | DataFrame |
|---------|--------|-----------|
| Dimension | 1D | 2D |
| Structure | Single column | Multiple columns |
| Index | ✅ | ✅ |
| Column Names | ❌ | ✅ |
| Can store multiple data types | ❌ (per Series) | ✅ |

> **Note:** A **Series** represents a single column of data, while a **DataFrame** is a collection of one or more Series organized into rows and columns.

---

### Making from dictionay

In [13]:

data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 21, 22]
}

df = pd.DataFrame(data , index = ["a", "b", "c"])
df

    Name  Age
a    Ali   20
b   Sara   21
c  Ahmed   22

### From a List of Lists

In [6]:
data = [
    ["Ali" , 84] , 
    ["Sara" , 90] ,
    ["Ahmed" , 95]
]

df = pd.DataFrame(data , columns=["Name" , "Marks"])
df

    Name  Marks
0    Ali     84
1   Sara     90
2  Ahmed     95

### From a NumPy Array

In [9]:



arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4
2  5  6

### From list of dictionaries

In [14]:
dada = [
    {"Name": "Ali", "Marks": 84},
    {"Name": "Sara", "Marks": 90},
    {"Name": "Ahmed", "Marks": 95}
]
df = pd.DataFrame(dada)
df

    Name  Marks
0    Ali     84
1   Sara     90
2  Ahmed     95

### From series

In [11]:
s = pd.Series([10, 20, 30])

df = pd.DataFrame(s, columns=["Marks"])
df

   Marks
0     10
1     20
2     30

### From csv

In [ ]:
df = pd.read_csv("data.csv") # no csv for now in folder 
df

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

### Basic thing about dataFrame

In [15]:

data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 21, 22]
}

df = pd.DataFrame(data , index = ["a", "b", "c"])
df

    Name  Age
a    Ali   20
b   Sara   21
c  Ahmed   22

In [16]:
df.shape

(3, 2)

In [17]:
df.size

6

In [18]:
df.ndim

2

In [19]:
df.dtypes

Name      str
Age     int64
dtype: object

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, a to c
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0+ bytes

In [21]:
df.describe()

        Age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0

In [22]:
df.head

<bound method NDFrame.head of     Name  Age
a    Ali   20
b   Sara   21
c  Ahmed   22>

In [23]:
df.tail

<bound method NDFrame.tail of     Name  Age
a    Ali   20
b   Sara   21
c  Ahmed   22>

In [ ]:
len(df)