# Reading Files in Pandas

# Author :  Muhammad Ali Saagar

**Python Developer • Data Science • AI/ML Enthusiast**

### 🔗 Connect With Me

[![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AliMuhammad78)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/muhammad-ali-91294a290)

[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/ali98muhammad45)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@TechyBits20121)

[![Instagram](https://img.shields.io/badge/Instagram-Profile-E4405F?style=for-the-badge\&logo=instagram)](https://www.instagram.com/alisaagar6453/)
[![Facebook](https://img.shields.io/badge/Facebook-Profile-1877F2?style=for-the-badge\&logo=facebook)](https://www.facebook.com/profile.php?id=100089566913912)

[![Email](https://img.shields.io/badge/Email-Contact-D14836?style=for-the-badge\&logo=gmail)](mailto:alisaagar86@gmail.com)

---

In [11]:
import numpy as np 
import pandas as pd

In [12]:
df = pd.read_csv('iris.csv' )
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [13]:
len(df)

150

In [14]:
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

---

In [15]:
import sqlite3
# Connect to the database
conn = sqlite3.connect("SaagarSports.db")

# Read the table
sports_data = pd.read_sql("SELECT * FROM products", conn)

sports_data

,id,name,category,description,price,image,stock
0,1,bat,bat,NaN,340.0,None,0
1,7,Football,Football,FIFA Quality Football,1200.0,None,30
2,8,Badminton Racket,Badminton,Lightweight Carbon Racket,2500.0,None,12
3,9,Cricket Bat,Cricket,Premium English Willow Bat,3400.0,None,15
4,10,Football,Football,FIFA Quality Football,1200.0,None,30
5,11,Badminton Racket,Badminton,Lightweight Carbon Racket,2500.0,None,12
6,12,Cricket Bat,Cricket,Premium English Willow Bat,3400.0,None,15
7,13,Football,Football,FIFA Quality Football,1200.0,None,30
8,14,Badminton Racket,Badminton,Lightweight Carbon Racket,2500.0,None,12
9,16,Football,Football,FIFA Quality Football,1200.0,None,30
10,17,Badminton Racket,Badminton,Lightweight Carbon Racket,2500.0,None,12
11,18,Cricket Bat,Cricket,Premium English Willow Bat,3400.0,None,15
12,19,Football,Football,FIFA Quality Football,1200.0,None,30
13,21,basketBall,Basketball,this si basket ball,234.0,None,45

In [16]:
conn.close()

In [17]:
sports_data.head(10)

,id,name,category,description,price,image,stock
0,1,bat,bat,NaN,340.0,None,0
1,7,Football,Football,FIFA Quality Football,1200.0,None,30
2,8,Badminton Racket,Badminton,Lightweight Carbon Racket,2500.0,None,12
3,9,Cricket Bat,Cricket,Premium English Willow Bat,3400.0,None,15
4,10,Football,Football,FIFA Quality Football,1200.0,None,30
5,11,Badminton Racket,Badminton,Lightweight Carbon Racket,2500.0,None,12
6,12,Cricket Bat,Cricket,Premium English Willow Bat,3400.0,None,15
7,13,Football,Football,FIFA Quality Football,1200.0,None,30
8,14,Badminton Racket,Badminton,Lightweight Carbon Racket,2500.0,None,12
9,16,Football,Football,FIFA Quality Football,1200.0,None,30

In [20]:
sports_data.to_csv('sports_data.csv', index=False)

In [18]:
df.tail(10)

     sepal_length  sepal_width  petal_length  petal_width         species
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [19]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000