# SELECTING SPECIFIC DATA USING PANDAS

# Author :  Muhammad Ali Saagar

**Python Developer • Data Science • AI/ML Enthusiast**

### 🔗 Connect With Me

[![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AliMuhammad78)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/muhammad-ali-91294a290)

[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/ali98muhammad45)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@TechyBits20121)

[![Instagram](https://img.shields.io/badge/Instagram-Profile-E4405F?style=for-the-badge\&logo=instagram)](https://www.instagram.com/alisaagar6453/)
[![Facebook](https://img.shields.io/badge/Facebook-Profile-1877F2?style=for-the-badge\&logo=facebook)](https://www.facebook.com/profile.php?id=100089566913912)

[![Email](https://img.shields.io/badge/Email-Contact-D14836?style=for-the-badge\&logo=gmail)](mailto:alisaagar86@gmail.com)

---

In [1]:
import numpy as np 
import pandas as pd 

df = pd.read_csv('iris.csv' )
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [7]:
type(df)

pandas.DataFrame

In [9]:

type(df["sepal_length"])

pandas.Series

In [12]:
df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [13]:
df[['sepal_length', 'sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

# 📌 Difference Between `loc[]` and `iloc[]`

| Feature | `loc[]` | `iloc[]` |
|---------|----------|-----------|
| Selection Type | Uses **labels (names)** | Uses **integer positions** |
| Row Selection | Row names/index labels | Row numbers (0, 1, 2, ...) |
| Column Selection | Column names | Column positions |
| Slice End | **Inclusive** | **Exclusive** |
| Best Used When | You know the row/column names | You know the row/column positions |

## Example

```python
import pandas as pd

df = pd.DataFrame(
    {
        "Name": ["Ali", "Sara", "Ahmed"],
        "Age": [20, 21, 22]
    },
    index=["A", "B", "C"]
)
```

### `loc[]` (Uses Labels)

```python
df.loc["A"]          # First row (label A)

df.loc[:, "Name"]    # Name column
```

### `iloc[]` (Uses Positions)

```python
df.iloc[0]           # First row (position 0)

df.iloc[:, 0]        # First column (position 0)
```

> **Easy Way to Remember**
>
> - **`loc` = Label-based indexing** (uses row/column **names**)
> - **`iloc` = Integer-location indexing** (uses row/column **positions**)

#### select first row

In [14]:
df.iloc[0]

sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
species         Iris-setosa
Name: 0, dtype: object

#### last row

In [15]:
df.iloc[-1]

sepal_length               5.9
sepal_width                3.0
petal_length               5.1
petal_width                1.8
species         Iris-virginica
Name: 149, dtype: object

#### first 5 rows

In [16]:
df.iloc[:5]

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

#### 10 to 20 rows

In [17]:
df.iloc[10 : 20 ]

    sepal_length  sepal_width  petal_length  petal_width      species
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
15           5.7          4.4           1.5          0.4  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
17           5.1          3.5           1.4          0.3  Iris-setosa
18           5.7          3.8           1.7          0.3  Iris-setosa
19           5.1          3.8           1.5          0.3  Iris-setosa

### Seelect first column

In [18]:
df.iloc[:, 0]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

### select specific value

#

In [19]:
df.iloc[5, 3] # row 5 , column 3

np.float64(0.4)

### Select rows and columns together

In [ ]:
df.iloc[0:5, 0:3] # frist 5 rows and first 3 columns

   sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5
4           5.0          3.6           1.4

### select specific rows

In [21]:
df.iloc[[0, 10, 50]]

    sepal_length  sepal_width  petal_length  petal_width          species
0            5.1          3.5           1.4          0.2      Iris-setosa
10           5.4          3.7           1.5          0.2      Iris-setosa
50           7.0          3.2           4.7          1.4  Iris-versicolor

In [22]:
df.loc[0:5, ['sepal_length', 'sepal_width']]

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6
5           5.4          3.9