# Working with Columns in Pandas

# Author :  Muhammad Ali Saagar

**Python Developer • Data Science • AI/ML Enthusiast**

### 🔗 Connect With Me

[![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AliMuhammad78)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/muhammad-ali-91294a290)

[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/ali98muhammad45)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@TechyBits20121)

[![Instagram](https://img.shields.io/badge/Instagram-Profile-E4405F?style=for-the-badge\&logo=instagram)](https://www.instagram.com/alisaagar6453/)
[![Facebook](https://img.shields.io/badge/Facebook-Profile-1877F2?style=for-the-badge\&logo=facebook)](https://www.facebook.com/profile.php?id=100089566913912)

[![Email](https://img.shields.io/badge/Email-Contact-D14836?style=for-the-badge\&logo=gmail)](mailto:alisaagar86@gmail.com)

---

## Add a New Column

In [2]:
import pandas as pd

df = pd.read_csv("iris.csv")

In [3]:
df["sepal_area"] = df['sepal_length'] * df['sepal_width']
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00

## Dropping rows and columns
##### drop()

In [4]:

# Removes rows or columns.

# Remove a column
df.drop("species", axis=1)

# Remove the first row
df.drop(0, axis=0)

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00
5,5.4,3.9,1.7,0.4,Iris-setosa,21.06
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70

In [5]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00

### remane column

In [ ]:
df.rename(columns={"species": "flower_species"},inplace=True)

In [10]:
df

,sepal_length,sepal_width,petal_length,petal_width,flower_species,sepal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,5.9,3.0,5.1,1.8,Iris-virginica,17.70

### Sorting values

In [8]:
df.sort_values(by="sepal_length", ascending=False)

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
131,7.9,3.8,6.4,2.0,Iris-virginica,30.02
122,7.7,2.8,6.7,2.0,Iris-virginica,21.56
118,7.7,2.6,6.9,2.3,Iris-virginica,20.02
117,7.7,3.8,6.7,2.2,Iris-virginica,29.26
135,7.7,3.0,6.1,2.3,Iris-virginica,23.10
...,...,...,...,...,...,...
41,4.5,2.3,1.3,0.3,Iris-setosa,10.35
42,4.4,3.2,1.3,0.2,Iris-setosa,14.08
8,4.4,2.9,1.4,0.2,Iris-setosa,12.76
38,4.4,3.0,1.3,0.2,Iris-setosa,13.20
13,4.3,3.0,1.1,0.1,Iris-setosa,12.90